# Generated by Django 5.1.2 on 2025-01-26 10:33

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Category_img')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('gmap', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='instructors')),
                ('name', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=200)),
                ('twt', models.CharField(max_length=200)),
                ('ig', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='courses/featured_img')),
                ('featured_video', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('student', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
            ],
        ),
    ]
